[package]
name = "suiami"
edition = "2024.beta"
published-at = "0xaf56e9d096a69ccc68486cfcc88d5ed08db1cf37c88d255ab14ba0e3a7ab39a0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
suiami = "0x2c1d63b3b314f9b6e96c33e9a3bca4faaa79a69a5729e5d2e8ac09d70e1052fa"
