// Copyright (c) 2026 Thunder Storm
// SPDX-License-Identifier: MIT

// Metal Claw tests — ecdsa_k1 EIP-191 roundtrip + set_ens_identity_verified.
//
// Fixtures are generated by `scripts/gen-metal-claw-fixture.ts` (viem-signed
// with test privkey 0x…01). Regenerate with `bun run scripts/gen-metal-claw-fixture.ts`
// if TEST_* constants drift.

#[test_only]
module suiami::metal_claw_tests;

use std::string;
use sui::clock;
use sui::test_scenario as ts;
use sui::ecdsa_k1;
use suiami::roster::{Self, Roster};

// ─── Fixtures (generated) ───────────────────────────────────────────
//
// ETH signer address: 0x7e5f4552091a69125d5dfcb7b8c2659029395bdf
// Inner message: "SUIAMI bind alice.waap.eth owner 0xabababababababababababababababababababababababababababababababab at 1734000000000"

const TEST_ETH_ADDR_BYTES: vector<u8> = vector[126u8, 95u8, 69u8, 82u8, 9u8, 26u8, 105u8, 18u8, 93u8, 93u8, 252u8, 183u8, 184u8, 194u8, 101u8, 144u8, 41u8, 57u8, 91u8, 223u8];
const TEST_ETH_ADDR_HEX: vector<u8> = b"0x7e5f4552091a69125d5dfcb7b8c2659029395bdf";
const TEST_SENDER: address = @0xabababababababababababababababababababababababababababababababab;
const TEST_ENS_NAME_BYTES: vector<u8> = vector[97u8, 108u8, 105u8, 99u8, 101u8, 46u8, 119u8, 97u8, 97u8, 112u8, 46u8, 101u8, 116u8, 104u8];
const TEST_TS_MS: u64 = 1734000000000;
const TEST_SIG: vector<u8> = vector[46u8, 236u8, 87u8, 113u8, 200u8, 209u8, 214u8, 76u8, 90u8, 112u8, 85u8, 27u8, 175u8, 146u8, 31u8, 33u8, 188u8, 12u8, 206u8, 63u8, 207u8, 11u8, 251u8, 216u8, 103u8, 178u8, 169u8, 171u8, 118u8, 220u8, 23u8, 163u8, 50u8, 175u8, 127u8, 221u8, 114u8, 89u8, 222u8, 251u8, 120u8, 200u8, 135u8, 168u8, 216u8, 178u8, 47u8, 193u8, 21u8, 229u8, 95u8, 14u8, 10u8, 19u8, 124u8, 154u8, 25u8, 151u8, 197u8, 150u8, 2u8, 30u8, 97u8, 78u8, 1u8];

// Error codes (mirror roster.move)
const EEthSigMismatch: u64 = 5;
const ETimestampSkew: u64 = 7;
const ENoEthSquid: u64 = 4;

// Arbitrary 32-byte ens_hash for test. Real clients compute keccak256(ens_name).
fun test_ens_hash(): vector<u8> {
    let mut h = vector::empty<u8>();
    let mut i = 0;
    while (i < 32) { h.push_back(0xCDu8); i = i + 1; };
    h
}

// ─── Pure-helper tests (no Roster needed) ───────────────────────────

#[test]
fun test_eip191_roundtrip() {
    // build_bind_inner_message + eip191_wrap → ecrecover → eth_address
    // should recover the address the signature was produced with.
    let ens_name = string::utf8(TEST_ENS_NAME_BYTES);
    let inner = roster::test_build_bind_inner_message(&ens_name, TEST_SENDER, TEST_TS_MS);
    let prefixed = roster::test_eip191_wrap(&inner);
    let compressed = ecdsa_k1::secp256k1_ecrecover(&TEST_SIG, &prefixed, 0);
    let recovered = roster::test_pubkey_to_eth_address(&compressed);
    assert!(recovered == TEST_ETH_ADDR_BYTES, 0);
}

#[test]
fun test_eth_hex_parse_mixed_case() {
    // Mixed-case hex with 0x prefix must parse to the same 20 bytes.
    let s = string::utf8(b"0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf");
    let bytes = roster::test_eth_hex_string_to_bytes(&s);
    assert!(bytes == TEST_ETH_ADDR_BYTES, 0);
}

#[test]
fun test_u64_to_ascii_cases() {
    assert!(roster::test_u64_to_ascii_decimal(0) == vector[48u8], 0);
    assert!(roster::test_u64_to_ascii_decimal(1) == vector[49u8], 0);
    assert!(roster::test_u64_to_ascii_decimal(10) == vector[49u8, 48u8], 0);
    // 1734000000000 → "1734000000000"
    assert!(
        roster::test_u64_to_ascii_decimal(1734000000000)
            == vector[49u8, 55u8, 51u8, 52u8, 48u8, 48u8, 48u8, 48u8, 48u8, 48u8, 48u8, 48u8, 48u8],
        0,
    );
}

// ─── Integration tests (Roster + set_ens_identity_verified) ─────────

fun setup_with_eth_chain(scenario: &mut ts::Scenario, clock: &clock::Clock) {
    // First tx: init roster
    roster::init_for_testing(ts::ctx(scenario));
    ts::next_tx(scenario, TEST_SENDER);

    // Second tx: sender calls set_identity with an "eth" chain entry
    let mut r = ts::take_shared<Roster>(scenario);
    let chain_keys = vector[string::utf8(b"eth")];
    let chain_values = vector[string::utf8(TEST_ETH_ADDR_HEX)];
    roster::set_identity(
        &mut r,
        string::utf8(b"alice"),
        test_ens_hash(), // arbitrary name_hash for the SuiNS-side record
        chain_keys,
        chain_values,
        vector::empty<address>(),
        string::utf8(b""),
        vector::empty<u8>(),
        clock,
        ts::ctx(scenario),
    );
    ts::return_shared(r);
    ts::next_tx(scenario, TEST_SENDER);
}

#[test]
fun test_set_ens_identity_verified_happy() {
    let mut scenario = ts::begin(TEST_SENDER);
    let mut clk = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clk, TEST_TS_MS);

    setup_with_eth_chain(&mut scenario, &clk);

    let mut r = ts::take_shared<Roster>(&mut scenario);
    let ens_hash = vector[0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8,
                         0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8,
                         0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8,
                         0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8, 0xAAu8];
    roster::set_ens_identity_verified(
        &mut r,
        string::utf8(TEST_ENS_NAME_BYTES),
        ens_hash,
        TEST_SIG,
        TEST_TS_MS,
        &clk,
        ts::ctx(&mut scenario),
    );
    assert!(roster::has_ens_name(&r, ens_hash), 0);
    ts::return_shared(r);

    clock::destroy_for_testing(clk);
    ts::end(scenario);
}

#[test]
#[expected_failure(abort_code = EEthSigMismatch, location = suiami::roster)]
fun test_set_ens_identity_verified_bad_sig() {
    let mut scenario = ts::begin(TEST_SENDER);
    let mut clk = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clk, TEST_TS_MS);

    setup_with_eth_chain(&mut scenario, &clk);

    let mut r = ts::take_shared<Roster>(&mut scenario);
    // Flip a single byte in the signature (r[0]) — ecrecover returns a
    // different pubkey, recovered address won't match → EEthSigMismatch.
    let mut bad_sig = TEST_SIG;
    let byte0 = *bad_sig.borrow(0);
    *bad_sig.borrow_mut(0) = byte0 ^ 0x01u8;

    roster::set_ens_identity_verified(
        &mut r,
        string::utf8(TEST_ENS_NAME_BYTES),
        test_ens_hash(),
        bad_sig,
        TEST_TS_MS,
        &clk,
        ts::ctx(&mut scenario),
    );
    ts::return_shared(r);

    clock::destroy_for_testing(clk);
    ts::end(scenario);
}

#[test]
#[expected_failure(abort_code = ETimestampSkew, location = suiami::roster)]
fun test_set_ens_identity_verified_ts_skew() {
    let mut scenario = ts::begin(TEST_SENDER);
    let mut clk = clock::create_for_testing(ts::ctx(&mut scenario));
    // Clock 2 hours ahead of the signed timestamp → > 600_000 ms window.
    clock::set_for_testing(&mut clk, TEST_TS_MS + 7_200_000);

    setup_with_eth_chain(&mut scenario, &clk);

    let mut r = ts::take_shared<Roster>(&mut scenario);
    roster::set_ens_identity_verified(
        &mut r,
        string::utf8(TEST_ENS_NAME_BYTES),
        test_ens_hash(),
        TEST_SIG,
        TEST_TS_MS, // signed ts stays the same; clock drift triggers abort
        &clk,
        ts::ctx(&mut scenario),
    );
    ts::return_shared(r);

    clock::destroy_for_testing(clk);
    ts::end(scenario);
}

#[test]
#[expected_failure(abort_code = ENoEthSquid, location = suiami::roster)]
fun test_set_ens_identity_verified_no_eth_squid() {
    let mut scenario = ts::begin(TEST_SENDER);
    let mut clk = clock::create_for_testing(ts::ctx(&mut scenario));
    clock::set_for_testing(&mut clk, TEST_TS_MS);

    // Init + set_identity with ONLY a btc chain, no "eth" entry.
    roster::init_for_testing(ts::ctx(&mut scenario));
    ts::next_tx(&mut scenario, TEST_SENDER);

    let mut r = ts::take_shared<Roster>(&mut scenario);
    let chain_keys = vector[string::utf8(b"btc")];
    let chain_values = vector[string::utf8(b"bc1qexampleonly")];
    roster::set_identity(
        &mut r,
        string::utf8(b"alice"),
        test_ens_hash(),
        chain_keys,
        chain_values,
        vector::empty<address>(),
        string::utf8(b""),
        vector::empty<u8>(),
        &clk,
        ts::ctx(&mut scenario),
    );
    ts::return_shared(r);
    ts::next_tx(&mut scenario, TEST_SENDER);

    let mut r2 = ts::take_shared<Roster>(&mut scenario);
    roster::set_ens_identity_verified(
        &mut r2,
        string::utf8(TEST_ENS_NAME_BYTES),
        test_ens_hash(),
        TEST_SIG,
        TEST_TS_MS,
        &clk,
        ts::ctx(&mut scenario),
    );
    ts::return_shared(r2);

    clock::destroy_for_testing(clk);
    ts::end(scenario);
}
