// Generate test fixtures for Metal Claw (suiami::roster::set_ens_identity_verified).
//
// Outputs Move `vector[..u8]` literals matching the on-chain verifier's expected
// byte layout: EIP-191 personal-sign over `SUIAMI bind <ens_name> owner 0x<sui_sender_64hex> at <ts_ms>`.
//
// Run: `bun run scripts/gen-metal-claw-fixture.ts`

import { privateKeyToAccount } from 'viem/accounts';
import { hexToBytes } from 'viem';

const TEST_PRIVKEY = '0x0000000000000000000000000000000000000000000000000000000000000001' as const;
const TEST_SENDER_HEX = 'ab'.repeat(32); // 32-byte Sui address, lowercase 64 hex
const TEST_ENS_NAME = 'alice.waap.eth';
const TEST_TS_MS = 1_734_000_000_000n;

const account = privateKeyToAccount(TEST_PRIVKEY);
const inner = `SUIAMI bind ${TEST_ENS_NAME} owner 0x${TEST_SENDER_HEX} at ${TEST_TS_MS}`;

const sigHex = await account.signMessage({ message: inner });
const sigBytes = hexToBytes(sigHex);
// Normalize v byte: viem/eth convention returns 27|28, sui::ecdsa_k1 wants 0|1.
const v = sigBytes[64];
const normalized = new Uint8Array(sigBytes);
normalized[64] = v >= 27 ? v - 27 : v;

const ethAddrBytes = hexToBytes(account.address as `0x${string}`);

const toMoveVec = (b: Uint8Array) =>
    'vector[' + Array.from(b).map((n) => `${n}u8`).join(', ') + ']';

const ensNameBytes = new TextEncoder().encode(TEST_ENS_NAME);

console.log(`// Auto-generated by scripts/gen-metal-claw-fixture.ts — do not edit by hand.`);
console.log(`// ETH signer address: ${account.address}`);
console.log(`// Inner message: ${JSON.stringify(inner)}`);
console.log(``);
console.log(`const TEST_ETH_ADDR_BYTES: vector<u8> = ${toMoveVec(ethAddrBytes)};`);
console.log(`const TEST_ETH_ADDR_HEX: vector<u8> = b"${account.address.toLowerCase()}";`);
console.log(`const TEST_SENDER: address = @0x${TEST_SENDER_HEX};`);
console.log(`const TEST_ENS_NAME_BYTES: vector<u8> = ${toMoveVec(ensNameBytes)};`);
console.log(`const TEST_TS_MS: u64 = ${TEST_TS_MS};`);
console.log(`const TEST_SIG: vector<u8> = ${toMoveVec(normalized)};`);
